In [1]:
import pandas as pd
import requests
import os
from sqlalchemy import create_engine
from dotenv import load_dotenv

load_dotenv()

url = ('https://newsapi.org/v2/everything?'
       'q=Apple&'
       'from=2026-06-10&'
       'sortBy=popularity&'
       'apiKey=' + os.getenv('NEWS_API_KEY'))

response = requests.get(url)
response.json()

{'status': 'ok',
 'totalResults': 19728,
 'articles': [{'source': {'id': 'wired', 'name': 'Wired'},
   'author': 'Louryn Strampe',
   'title': 'Prime Day Means Apple Deals on iPad, iPhone Cases, MagSafe Accessories, and More',
   'description': "Apple deals abound for Amazon Prime Day. We've rounded up the best deals on Apple Watches, iPhones, MacBooks, iPads, and accessories.",
   'url': 'https://www.wired.com/story/best-prime-day-apple-deals-2026/',
   'urlToImage': 'https://media.wired.com/photos/6a39bf7f0bf55f5b8a30365a/191:100/w_1280,c_limit/The-Best-Prime-Day-Apple-Deals-on-AirPods,-iPads,-and-More.jpg',
   'publishedAt': '2026-06-23T08:57:27Z',
   'content': 'Amazon Prime Day is one of the most reliable ways to save on Apple devices. Apple gadgets go on sale pretty often, but Prime Day brings the broadest opportunities, with deals and discounts on basical… [+1079 chars]'},
  {'source': {'id': 'wired', 'name': 'Wired'},
   'author': 'Julian Chokkattu',
   'title': 'How Apple Is Making Your Older iPhone Run Faster and Stay Alive Longer',
   'description': 'Even the aging iPhone 11 will feel a little more responsive soon, thanks to improvements in an unsung iOS feature.',
   'url': 'https://www.wired.com/story/how-apple-is-making-your-older-iphone-run-faster-and-stay-alive-longer/',
   'urlToImage': 'https://media.wired.com/photos/6a2aabf0a0ec339aba978ccf/191:100/w_1280,c_limit/GettyImages-1209226885.jpg',
   'publishedAt': '2026-06-15T10:30:00Z',
   'content': "Your aging iPhone will feel a little more responsive once you download iOS 27 later this year. At least, that's Apple's claim. At its developer keynote at this years WWDC, the company said its next m… [+2318 chars]"},
  {'source': {'id': 'wired', 'name': 'Wired'},
   'author': 'Louryn Strampe',
   'title': 'Verizon Simplicity, Verizon Shine, and Verizon Dollars: What You Need to Know',
   'description': 'Verizon introduced a new plan that costs $45 per month, revamped rewards programs, and more today.',
   'url': 'https://www.wired.com/story/verizon-simplicity-plan/',
   'urlToImage': 'https://media.wired.com/photos/6a303c55d7c81c31bb89b0ff/191:100/w_1280,c_limit/The-New-Verizon-Simplicity-Plan-Takes-The-Guesswork-Away.jpg',
   'publishedAt': '2026-06-16T15:06:22Z',
   'content': "I've been aVerizon customer since T-Mobile and Sprint merged, and I've always had consistent luck getting solid service, even in crowded environments and intense weather. This year, I moved states an… [+4660 chars]"},
  {'source': {'id': 'wired', 'name': 'Wired'},
   'author': 'Boutayna Chokrane',
   'title': 'Best Prime Day Fitness Tech Deals (2026)',
   'description': "Shopping Amazon's sale for yourself or a loved one? Here are the best Prime Day fitness tech deals, including smartwatches, walking pads, and recovery gear.",
   'url': 'https://www.wired.com/story/amazon-prime-day-fitness-deals-2026/',
   'urlToImage': 'https://media.wired.com/photos/6a3a246397b3e5bb7d92cfe0/191:100/w_1280,c_limit/The-Best-Fitness-Tech-Deals-This-Amazon-Prime-Day.jpg',
   'publishedAt': '2026-06-23T09:32:14Z',
   'content': "For Amazon's summer sale event, I've compiled a list of the best Prime Day fitness tech deals on our favorite gadgets. From smartwatches and fitness trackers to walking pads and recovery gear, we've … [+5866 chars]"},
  {'source': {'id': 'wired', 'name': 'Wired'},
   'author': 'Maxwell Zeff',
   'title': 'The White House Is Making Up Its Rules for AI in Real Time',
   'description': 'Anthropic still can’t distribute Claude Mythos or Fable 5 after running afoul of the Trump administration. But no one can say exactly what the company did wrong.',
   'url': 'https://www.wired.com/story/anthropic-mythos-export-controls-ai-regulations/',
   'urlToImage': 'https://media.wired.com/photos/6a342bff039398b1addb3ba2/191:100/w_1280,c_limit/Model-Behavior-SB.jpg',
   'publishedAt': '2026-06-18T21:03:43Z',
   'content': 'Its been nearly a week since the Trump administration sent an export control directive to Anthropic, forcing one of the worlds leading AI labs to pull its most advanced models offline. After days of … [+3695 chars]'},
  {'source': {'id': 'wired', 'name': 'Wired'},
   'author': 'Vittoria Elliott',
   'title': 'Federal Workers Can’t Get the White House’s App Off Their Phones',
   'description': '“I deleted it as a test and it came immediately back,” says one government employee.',
   'url': 'https://www.wired.com/story/story/government-workers-cant-get-the-white-houses-app-off-their-phones/',
   'urlToImage': 'https://media.wired.com/photos/6a399c80ea2c52b725f772f1/191:100/w_1280,c_limit/Politics_FederalWorkersCantGettheWhiteHouseAppOffTheirPhones_v3.jpg',
   'publishedAt': '2026-06-23T10:00:00Z',
   'content': 'In May, theWhite House announced that its new app would be automatically downloaded onto the work phones of millions of government employees. The problem: Federal workers hate it and cant get rid of … [+3430 chars]'},
  {'source': {'id': 'wired', 'name': 'Wired'},
   'author': 'Dan Goodin, Ars Technica',
   'title': 'A Critical Deadline Is Approaching for Windows and Linux Security',
   'description': "The cryptographic keys that secure your computer's boot sequence will start to expire on June 24. Here's what that means for you.",
   'url': 'https://www.wired.com/story/a-critical-deadline-is-approaching-for-windows-and-linux-security/',
   'urlToImage': 'https://media.wired.com/photos/6a342b0819ec74e5dcd4e6ca/191:100/w_1280,c_limit/GettyImages-1091064696.jpg',
   'publishedAt': '2026-06-21T09:00:00Z',
   'content': 'The clock is ticking for Windows and Linux users to update cryptographic keys that protect their systems against firmware-based UEFI infections, a pernicious form of malware that loads before operati… [+4209 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Jennifer Pattison Tuohy',
   'title': 'Apple, Google add support for Thread 1.4',
   'description': 'Apple and Google are updating their smart home streaming devices to Thread 1.4. As first spotted by Matter Alpha and 9to5 Google, the latest spec has arrived on compatible Apple TVs in the tvOS 27 developer beta and the Google TV Streamer through a software u…',
   'url': 'https://www.theverge.com/tech/947888/apple-google-add-support-for-thread-1-4',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/IMG_7137.jpg?quality=90&strip=all&crop=0%2C30.191972076789%2C100%2C69.808027923211&w=1200',
   'publishedAt': '2026-06-10T20:30:33Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nIts almost time for one big Thread network!\r\nIts almost time for one big Thread network!\r\nby\r\nJennifer Pattison TuohyClose\r\nSenior Reviewer, Smart Home\r\nPosts fr… [+3614 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Janko Roettgers',
   'title': 'Is Apple TV the new HBO?',
   'description': 'This is Lowpass by Janko Roettgers, a newsletter on the ever-evolving intersection of tech and entertainment, syndicated just for The Verge subscribers once a week. Severance. Pachinko. Silo. Ted Lasso. Over the past couple of years, a number of Apple TV show…',
   'url': 'https://www.theverge.com/column/948295/apple-tv-new-hbo',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2025/03/Severance_Photo_020912.jpg?quality=90&strip=all&crop=0%2C10.726247800535%2C100%2C78.54750439893&w=1200',
   'publishedAt': '2026-06-11T12:19:25Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nUnlike competitors like Netflix, Apple TV emphasizes tentpole titles over large catalogs.\r\nUnlike competitors like Netflix, Apple TV emphasizes tentpole titles o… [+6523 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Sheena Vasani',
   'title': 'The Apple Watch Series 11 is back to its best price',
   'description': 'Apple’s upcoming watchOS 27 update will bring Siri AI and other exciting features to the Apple Watch Series 9 and newer Apple Watch models. If you’re contemplating an upgrade, all colorways of the GPS-enabled 42mm Apple Watch Series 11 — the latest model — ar…',
   'url': 'https://www.theverge.com/gadgets/947773/apple-watch-series-11-beats-studio-buds-plus-deal-sale',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2025/12/Apple-Watch-Series-11-deal.png?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-06-10T14:57:20Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nThe slick Beats Studio Buds Plus are also on sale for just $100, and Fujifilms fun Instax Mini 12 is even cheaper.\r\nThe slick Beats Studio Buds Plus are also on … [+4447 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Jess Weatherbed',
   'title': 'Bob Iger’s Disney wanted Apple, Twitter, and 007',
   'description': "Bob Iger's tenure as CEO of Disney came to an end a few months ago, after two decades of leading the entertainment giant through some of its most pivotal transformations and acquisitions. Iger, in an exit interview with The Financial Times, has now confirmed …",
   'url': 'https://www.theverge.com/streaming/955646/disney-bob-iger-twitter-james-bond-apple-merger',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/gettyimages-2179288051.jpg?quality=90&strip=all&crop=0%2C10.726302820383%2C100%2C78.547394359233&w=1200',
   'publishedAt': '2026-06-24T10:08:52Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nAn exit interview with the former Disney CEO confirms the massive deals that got away.\r\nAn exit interview with the former Disney CEO confirms the massive deals t… [+3848 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Emma Roth',
   'title': 'Tim Cook says RAM expenses are ‘unsustainable’ and Apple is going to raise prices',
   'description': 'Apple is planning to raise prices in response to the ongoing memory shortage. In an interview with The Wall Street Journal, Apple CEO Tim Cook says "price increases are unavoidable:" We\'re doing our best to mitigate the huge increases that are being passed to…',
   'url': 'https://www.theverge.com/tech/951948/apple-tim-cook-price-increases-ram',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2025/09/257981_Techwoven_AJohnson_0002.jpg?quality=90&strip=all&crop=0%2C10.723165084465%2C100%2C78.55366983107&w=1200',
   'publishedAt': '2026-06-17T21:45:12Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nPrice hikes could be coming to the iPhone, iPad, and Mac.\r\nPrice hikes could be coming to the iPhone, iPad, and Mac.\r\nby\r\nEmma RothClose\r\nPosts from this author … [+2695 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Jennifer Pattison Tuohy',
   'title': 'Apple’s smart home camera service is starting to impress me',
   'description': "Apple's HomeKit Secure Video service is getting in on the Apple Intelligence party to bring more descriptive alerts from your connected cameras and let you search footage using natural language. The Apple Home app is also getting better notifications powered …",
   'url': 'https://www.theverge.com/tech/949854/first-look-apple-home-ios-27-upgrades-homekit-secure-video',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/268594_iOS_27_home_app_first_look_CVirginia2.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-06-16T11:42:57Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\niOS 27 brings AI-powered summaries, natural-language search, and improved reliability to Apples HomeKit Secure Video making it much more competitive.\r\niOS 27 bri… [+8683 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Richard Lawler',
   'title': 'Apple 2027 rumors: AirPods with cameras for AI and the second folding iPhone',
   'description': "Now that we're clear of WWDC and all of the AI-powered features coming to Apple's platforms, Bloomberg reporter Mark Gurman has more details about rumored new hardware like the camera-equipped AirPods he'd previously written about. He says they are currently …",
   'url': 'https://www.theverge.com/tech/950826/apple-airpod-camera-ai-foldable-iphone-rumor',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2025/09/257943_Airpods_Pro3_AKrales_0078.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-06-16T17:06:46Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nAll leading up to the eventual smart glasses.\r\nAll leading up to the eventual smart glasses.\r\nby\r\nRichard LawlerClose\r\nPosts from this author will be added to yo… [+3951 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Jennifer Pattison Tuohy',
   'title': 'Thread Direct looks to solve Matter’s biggest setup headache',
   'description': 'The smart home networking protocol Thread is adding a new way to onboard devices without a Thread border router. The feature, called Thread Direct, is designed to let users set up Thread-powered devices - such as smart plugs and smart locks - using only a pho…',
   'url': 'https://www.theverge.com/tech/950732/thread-direct-thread-2-0-smart-home-apple-google',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2025/06/VRG_ILLO_5281_ThreadGroup_Matter.webp?quality=90&strip=all&crop=0%2C10.330086736612%2C100%2C79.339826526775&w=1200',
   'publishedAt': '2026-06-16T20:58:26Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nThe new feature will let phones with Thread radios onboard devices without needing a border router.\r\nThe new feature will let phones with Thread radios onboard d… [+5901 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'David Pierce',
   'title': 'Siri is good now??',
   'description': 'You\'d be forgiven for thinking this day would never come. Siri has spent a decade and half somewhere between "sort of useful at a few things" and "utterly disastrous, why did I even try, can it honestly not even set a timer." But the wildest thing just happen…',
   'url': 'https://www.theverge.com/podcast/949079/siri-ai-good-vergecast',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/VST_0612_Site.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-06-12T17:17:04Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nOn The Vergecast: Our first days with Siri AI, the next phase of social networks, and the Trump Phones a ripoff.\r\nOn The Vergecast: Our first days with Siri AI, … [+3128 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Sheena Vasani',
   'title': 'Apple’s latest AirTags are cheaper than ever for Prime Day',
   'description': 'Prime Day has brought a number of Apple deals, but one of the most useful if you’re planning to travel over the July 4th weekend or later this summer is on the new AirTags. The four-pack has dropped to a new low of $90 ($9 off) at Amazon and Best Buy, bringin…',
   'url': 'https://www.theverge.com/gadgets/951987/apple-airtag-second-gen-prime-day-deal-sale-2026',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/268280_AirTags_2_AKrales_0003.webp?quality=90&strip=all&crop=0,10.732984293194,100,78.534031413613',
   'publishedAt': '2026-06-22T14:36:39Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nThe four-pack is down to $90, marking the first major discount on Apples new item trackers.\r\nThe four-pack is down to $90, marking the first major discount on Ap… [+2885 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Antonio G. Di Benedetto',
   'title': 'My first 24 hours with Siri AI on the Mac',
   'description': "I turned off Siri on the Mac years ago and never looked back. Similarly, I found Apple Intelligence so fruitless I never engage with it. But the new Siri AI coming to macOS 27 Golden Gate has at least got me slightly rethinking things. I'm still early in test…",
   'url': 'https://www.theverge.com/tech/949502/apple-macos-27-golden-gate-siri-ai-apple-intelligence',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/061326_Siri_AI_MacBook_Pro_macOS_27_Golden_Gate_beta_ADiBenedetto_0003.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-06-13T13:44:07Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nMy first 24 hours with Siri AI on the Mac\r\nSiri is better, but its limitations are much more obvious on a Mac than an iPhone.\r\nby\r\nAntonio G. Di BenedettoClose\r\n… [+8253 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Terrence O’Brien',
   'title': 'Deezer launches an AI music detector for other streaming services',
   'description': "Deezer will now scan your playlists on other streaming platforms to detect AI-generated music. Deezer was the first of the big streaming services to start labeling AI-generated music. It even offered its tech to other platforms, but it doesn't seem like it ha…",
   'url': 'https://www.theverge.com/ai-artificial-intelligence/948153/deezer-ai-music-detector-spotify-apple',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/NEW_1200-x-580-pixel-SI-logo-1240x600-1.jpeg?quality=90&strip=all&crop=3.7903225806452,0,92.41935483871,100',
   'publishedAt': '2026-06-10T23:42:48Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nSince the competition wont buy their tech, theyre bringing it directly to users.\r\nSince the competition wont buy their tech, theyre bringing it directly to users… [+2359 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Jess Weatherbed',
   'title': 'Schlage’s UWB-enabled smart lock launches this month',
   'description': "It's been more than a year since Schlage announced its first smart lock to support ultra wideband technology (UWB), but now it's finally almost available to purchase. Starting June 29th, the Schlage Sense Pro deadbolt lock will be available for $399 in the US…",
   'url': 'https://www.theverge.com/tech/950564/schlage-sense-pro-uwb-aliro-deadlock-price-availability',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/ENTRYWAY_BE889_SEP622_DAV_COL_EXT_IU_01-1.jpg?quality=90&strip=all&crop=0%2C11.874755925629%2C100%2C76.250488148741&w=1200',
   'publishedAt': '2026-06-16T11:37:08Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nThe Schlage Sense Pro will work with Apples Home Key hands-free unlocking and is its first to support Matter and Thread.\r\nThe Schlage Sense Pro will work with Ap… [+3213 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'John.Higgins',
   'title': 'These are my favorite Prime Day deals on earbuds and headphones',
   'description': 'I can’t think of a tech accessory I actively use more than headphones. Whether it’s for music, calls, or just to block out ambient noise so I can focus, I always have a pair close at hand. One of the best times to get some of your own with some big savings at…',
   'url': 'https://www.theverge.com/gadgets/952601/earbuds-headphones-deals-prime-day-2026',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/chorus/uploads/chorus_asset/file/23454336/DSCF7813.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-06-23T12:06:56Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nNeed ANC, great sound, and something for a workout? Prime Day is the time to get some new headphones.\r\nNeed ANC, great sound, and something for a workout? Prime … [+5856 chars]'},

In [2]:
data = response.json()
type(data)

dict

In [3]:
articles =data['articles']
type(articles)
articles

[{'source': {'id': 'wired', 'name': 'Wired'},
  'author': 'Louryn Strampe',
  'title': 'Prime Day Means Apple Deals on iPad, iPhone Cases, MagSafe Accessories, and More',
  'description': "Apple deals abound for Amazon Prime Day. We've rounded up the best deals on Apple Watches, iPhones, MacBooks, iPads, and accessories.",
  'url': 'https://www.wired.com/story/best-prime-day-apple-deals-2026/',
  'urlToImage': 'https://media.wired.com/photos/6a39bf7f0bf55f5b8a30365a/191:100/w_1280,c_limit/The-Best-Prime-Day-Apple-Deals-on-AirPods,-iPads,-and-More.jpg',
  'publishedAt': '2026-06-23T08:57:27Z',
  'content': 'Amazon Prime Day is one of the most reliable ways to save on Apple devices. Apple gadgets go on sale pretty often, but Prime Day brings the broadest opportunities, with deals and discounts on basical… [+1079 chars]'},
 {'source': {'id': 'wired', 'name': 'Wired'},
  'author': 'Julian Chokkattu',
  'title': 'How Apple Is Making Your Older iPhone Run Faster and Stay Alive Longer',
  'description': 'Even the aging iPhone 11 will feel a little more responsive soon, thanks to improvements in an unsung iOS feature.',
  'url': 'https://www.wired.com/story/how-apple-is-making-your-older-iphone-run-faster-and-stay-alive-longer/',
  'urlToImage': 'https://media.wired.com/photos/6a2aabf0a0ec339aba978ccf/191:100/w_1280,c_limit/GettyImages-1209226885.jpg',
  'publishedAt': '2026-06-15T10:30:00Z',
  'content': "Your aging iPhone will feel a little more responsive once you download iOS 27 later this year. At least, that's Apple's claim. At its developer keynote at this years WWDC, the company said its next m… [+2318 chars]"},
 {'source': {'id': 'wired', 'name': 'Wired'},
  'author': 'Louryn Strampe',
  'title': 'Verizon Simplicity, Verizon Shine, and Verizon Dollars: What You Need to Know',
  'description': 'Verizon introduced a new plan that costs $45 per month, revamped rewards programs, and more today.',
  'url': 'https://www.wired.com/story/verizon-simplicity-plan/',
  'urlToImage': 'https://media.wired.com/photos/6a303c55d7c81c31bb89b0ff/191:100/w_1280,c_limit/The-New-Verizon-Simplicity-Plan-Takes-The-Guesswork-Away.jpg',
  'publishedAt': '2026-06-16T15:06:22Z',
  'content': "I've been aVerizon customer since T-Mobile and Sprint merged, and I've always had consistent luck getting solid service, even in crowded environments and intense weather. This year, I moved states an… [+4660 chars]"},
 {'source': {'id': 'wired', 'name': 'Wired'},
  'author': 'Boutayna Chokrane',
  'title': 'Best Prime Day Fitness Tech Deals (2026)',
  'description': "Shopping Amazon's sale for yourself or a loved one? Here are the best Prime Day fitness tech deals, including smartwatches, walking pads, and recovery gear.",
  'url': 'https://www.wired.com/story/amazon-prime-day-fitness-deals-2026/',
  'urlToImage': 'https://media.wired.com/photos/6a3a246397b3e5bb7d92cfe0/191:100/w_1280,c_limit/The-Best-Fitness-Tech-Deals-This-Amazon-Prime-Day.jpg',
  'publishedAt': '2026-06-23T09:32:14Z',
  'content': "For Amazon's summer sale event, I've compiled a list of the best Prime Day fitness tech deals on our favorite gadgets. From smartwatches and fitness trackers to walking pads and recovery gear, we've … [+5866 chars]"},
 {'source': {'id': 'wired', 'name': 'Wired'},
  'author': 'Maxwell Zeff',
  'title': 'The White House Is Making Up Its Rules for AI in Real Time',
  'description': 'Anthropic still can’t distribute Claude Mythos or Fable 5 after running afoul of the Trump administration. But no one can say exactly what the company did wrong.',
  'url': 'https://www.wired.com/story/anthropic-mythos-export-controls-ai-regulations/',
  'urlToImage': 'https://media.wired.com/photos/6a342bff039398b1addb3ba2/191:100/w_1280,c_limit/Model-Behavior-SB.jpg',
  'publishedAt': '2026-06-18T21:03:43Z',
  'content': 'Its been nearly a week since the Trump administration sent an export control directive to Anthropic, forcing one of the worlds leading AI labs to pull its most advanced models offline. After days of … [+3695 chars]'},
 {'source': {'id': 'wired', 'name': 'Wired'},
  'author': 'Vittoria Elliott',
  'title': 'Federal Workers Can’t Get the White House’s App Off Their Phones',
  'description': '“I deleted it as a test and it came immediately back,” says one government employee.',
  'url': 'https://www.wired.com/story/story/government-workers-cant-get-the-white-houses-app-off-their-phones/',
  'urlToImage': 'https://media.wired.com/photos/6a399c80ea2c52b725f772f1/191:100/w_1280,c_limit/Politics_FederalWorkersCantGettheWhiteHouseAppOffTheirPhones_v3.jpg',
  'publishedAt': '2026-06-23T10:00:00Z',
  'content': 'In May, theWhite House announced that its new app would be automatically downloaded onto the work phones of millions of government employees. The problem: Federal workers hate it and cant get rid of … [+3430 chars]'},
 {'source': {'id': 'wired', 'name': 'Wired'},
  'author': 'Dan Goodin, Ars Technica',
  'title': 'A Critical Deadline Is Approaching for Windows and Linux Security',
  'description': "The cryptographic keys that secure your computer's boot sequence will start to expire on June 24. Here's what that means for you.",
  'url': 'https://www.wired.com/story/a-critical-deadline-is-approaching-for-windows-and-linux-security/',
  'urlToImage': 'https://media.wired.com/photos/6a342b0819ec74e5dcd4e6ca/191:100/w_1280,c_limit/GettyImages-1091064696.jpg',
  'publishedAt': '2026-06-21T09:00:00Z',
  'content': 'The clock is ticking for Windows and Linux users to update cryptographic keys that protect their systems against firmware-based UEFI infections, a pernicious form of malware that loads before operati… [+4209 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Jennifer Pattison Tuohy',
  'title': 'Apple, Google add support for Thread 1.4',
  'description': 'Apple and Google are updating their smart home streaming devices to Thread 1.4. As first spotted by Matter Alpha and 9to5 Google, the latest spec has arrived on compatible Apple TVs in the tvOS 27 developer beta and the Google TV Streamer through a software u…',
  'url': 'https://www.theverge.com/tech/947888/apple-google-add-support-for-thread-1-4',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/IMG_7137.jpg?quality=90&strip=all&crop=0%2C30.191972076789%2C100%2C69.808027923211&w=1200',
  'publishedAt': '2026-06-10T20:30:33Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nIts almost time for one big Thread network!\r\nIts almost time for one big Thread network!\r\nby\r\nJennifer Pattison TuohyClose\r\nSenior Reviewer, Smart Home\r\nPosts fr… [+3614 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Janko Roettgers',
  'title': 'Is Apple TV the new HBO?',
  'description': 'This is Lowpass by Janko Roettgers, a newsletter on the ever-evolving intersection of tech and entertainment, syndicated just for The Verge subscribers once a week. Severance. Pachinko. Silo. Ted Lasso. Over the past couple of years, a number of Apple TV show…',
  'url': 'https://www.theverge.com/column/948295/apple-tv-new-hbo',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2025/03/Severance_Photo_020912.jpg?quality=90&strip=all&crop=0%2C10.726247800535%2C100%2C78.54750439893&w=1200',
  'publishedAt': '2026-06-11T12:19:25Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nUnlike competitors like Netflix, Apple TV emphasizes tentpole titles over large catalogs.\r\nUnlike competitors like Netflix, Apple TV emphasizes tentpole titles o… [+6523 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Sheena Vasani',
  'title': 'The Apple Watch Series 11 is back to its best price',
  'description': 'Apple’s upcoming watchOS 27 update will bring Siri AI and other exciting features to the Apple Watch Series 9 and newer Apple Watch models. If you’re contemplating an upgrade, all colorways of the GPS-enabled 42mm Apple Watch Series 11 — the latest model — ar…',
  'url': 'https://www.theverge.com/gadgets/947773/apple-watch-series-11-beats-studio-buds-plus-deal-sale',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2025/12/Apple-Watch-Series-11-deal.png?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
  'publishedAt': '2026-06-10T14:57:20Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nThe slick Beats Studio Buds Plus are also on sale for just $100, and Fujifilms fun Instax Mini 12 is even cheaper.\r\nThe slick Beats Studio Buds Plus are also on … [+4447 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Jess Weatherbed',
  'title': 'Bob Iger’s Disney wanted Apple, Twitter, and 007',
  'description': "Bob Iger's tenure as CEO of Disney came to an end a few months ago, after two decades of leading the entertainment giant through some of its most pivotal transformations and acquisitions. Iger, in an exit interview with The Financial Times, has now confirmed …",
  'url': 'https://www.theverge.com/streaming/955646/disney-bob-iger-twitter-james-bond-apple-merger',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/gettyimages-2179288051.jpg?quality=90&strip=all&crop=0%2C10.726302820383%2C100%2C78.547394359233&w=1200',
  'publishedAt': '2026-06-24T10:08:52Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nAn exit interview with the former Disney CEO confirms the massive deals that got away.\r\nAn exit interview with the former Disney CEO confirms the massive deals t… [+3848 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Emma Roth',
  'title': 'Tim Cook says RAM expenses are ‘unsustainable’ and Apple is going to raise prices',
  'description': 'Apple is planning to raise prices in response to the ongoing memory shortage. In an interview with The Wall Street Journal, Apple CEO Tim Cook says "price increases are unavoidable:" We\'re doing our best to mitigate the huge increases that are being passed to…',
  'url': 'https://www.theverge.com/tech/951948/apple-tim-cook-price-increases-ram',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2025/09/257981_Techwoven_AJohnson_0002.jpg?quality=90&strip=all&crop=0%2C10.723165084465%2C100%2C78.55366983107&w=1200',
  'publishedAt': '2026-06-17T21:45:12Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nPrice hikes could be coming to the iPhone, iPad, and Mac.\r\nPrice hikes could be coming to the iPhone, iPad, and Mac.\r\nby\r\nEmma RothClose\r\nPosts from this author … [+2695 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Jennifer Pattison Tuohy',
  'title': 'Apple’s smart home camera service is starting to impress me',
  'description': "Apple's HomeKit Secure Video service is getting in on the Apple Intelligence party to bring more descriptive alerts from your connected cameras and let you search footage using natural language. The Apple Home app is also getting better notifications powered …",
  'url': 'https://www.theverge.com/tech/949854/first-look-apple-home-ios-27-upgrades-homekit-secure-video',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/268594_iOS_27_home_app_first_look_CVirginia2.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
  'publishedAt': '2026-06-16T11:42:57Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\niOS 27 brings AI-powered summaries, natural-language search, and improved reliability to Apples HomeKit Secure Video making it much more competitive.\r\niOS 27 bri… [+8683 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Richard Lawler',
  'title': 'Apple 2027 rumors: AirPods with cameras for AI and the second folding iPhone',
  'description': "Now that we're clear of WWDC and all of the AI-powered features coming to Apple's platforms, Bloomberg reporter Mark Gurman has more details about rumored new hardware like the camera-equipped AirPods he'd previously written about. He says they are currently …",
  'url': 'https://www.theverge.com/tech/950826/apple-airpod-camera-ai-foldable-iphone-rumor',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2025/09/257943_Airpods_Pro3_AKrales_0078.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
  'publishedAt': '2026-06-16T17:06:46Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nAll leading up to the eventual smart glasses.\r\nAll leading up to the eventual smart glasses.\r\nby\r\nRichard LawlerClose\r\nPosts from this author will be added to yo… [+3951 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Jennifer Pattison Tuohy',
  'title': 'Thread Direct looks to solve Matter’s biggest setup headache',
  'description': 'The smart home networking protocol Thread is adding a new way to onboard devices without a Thread border router. The feature, called Thread Direct, is designed to let users set up Thread-powered devices - such as smart plugs and smart locks - using only a pho…',
  'url': 'https://www.theverge.com/tech/950732/thread-direct-thread-2-0-smart-home-apple-google',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2025/06/VRG_ILLO_5281_ThreadGroup_Matter.webp?quality=90&strip=all&crop=0%2C10.330086736612%2C100%2C79.339826526775&w=1200',
  'publishedAt': '2026-06-16T20:58:26Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nThe new feature will let phones with Thread radios onboard devices without needing a border router.\r\nThe new feature will let phones with Thread radios onboard d… [+5901 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'David Pierce',
  'title': 'Siri is good now??',
  'description': 'You\'d be forgiven for thinking this day would never come. Siri has spent a decade and half somewhere between "sort of useful at a few things" and "utterly disastrous, why did I even try, can it honestly not even set a timer." But the wildest thing just happen…',
  'url': 'https://www.theverge.com/podcast/949079/siri-ai-good-vergecast',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/VST_0612_Site.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
  'publishedAt': '2026-06-12T17:17:04Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nOn The Vergecast: Our first days with Siri AI, the next phase of social networks, and the Trump Phones a ripoff.\r\nOn The Vergecast: Our first days with Siri AI, … [+3128 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Sheena Vasani',
  'title': 'Apple’s latest AirTags are cheaper than ever for Prime Day',
  'description': 'Prime Day has brought a number of Apple deals, but one of the most useful if you’re planning to travel over the July 4th weekend or later this summer is on the new AirTags. The four-pack has dropped to a new low of $90 ($9 off) at Amazon and Best Buy, bringin…',
  'url': 'https://www.theverge.com/gadgets/951987/apple-airtag-second-gen-prime-day-deal-sale-2026',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/268280_AirTags_2_AKrales_0003.webp?quality=90&strip=all&crop=0,10.732984293194,100,78.534031413613',
  'publishedAt': '2026-06-22T14:36:39Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nThe four-pack is down to $90, marking the first major discount on Apples new item trackers.\r\nThe four-pack is down to $90, marking the first major discount on Ap… [+2885 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Antonio G. Di Benedetto',
  'title': 'My first 24 hours with Siri AI on the Mac',
  'description': "I turned off Siri on the Mac years ago and never looked back. Similarly, I found Apple Intelligence so fruitless I never engage with it. But the new Siri AI coming to macOS 27 Golden Gate has at least got me slightly rethinking things. I'm still early in test…",
  'url': 'https://www.theverge.com/tech/949502/apple-macos-27-golden-gate-siri-ai-apple-intelligence',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/061326_Siri_AI_MacBook_Pro_macOS_27_Golden_Gate_beta_ADiBenedetto_0003.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
  'publishedAt': '2026-06-13T13:44:07Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nMy first 24 hours with Siri AI on the Mac\r\nSiri is better, but its limitations are much more obvious on a Mac than an iPhone.\r\nby\r\nAntonio G. Di BenedettoClose\r\n… [+8253 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Terrence O’Brien',
  'title': 'Deezer launches an AI music detector for other streaming services',
  'description': "Deezer will now scan your playlists on other streaming platforms to detect AI-generated music. Deezer was the first of the big streaming services to start labeling AI-generated music. It even offered its tech to other platforms, but it doesn't seem like it ha…",
  'url': 'https://www.theverge.com/ai-artificial-intelligence/948153/deezer-ai-music-detector-spotify-apple',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/NEW_1200-x-580-pixel-SI-logo-1240x600-1.jpeg?quality=90&strip=all&crop=3.7903225806452,0,92.41935483871,100',
  'publishedAt': '2026-06-10T23:42:48Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nSince the competition wont buy their tech, theyre bringing it directly to users.\r\nSince the competition wont buy their tech, theyre bringing it directly to users… [+2359 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Jess Weatherbed',
  'title': 'Schlage’s UWB-enabled smart lock launches this month',
  'description': "It's been more than a year since Schlage announced its first smart lock to support ultra wideband technology (UWB), but now it's finally almost available to purchase. Starting June 29th, the Schlage Sense Pro deadbolt lock will be available for $399 in the US…",
  'url': 'https://www.theverge.com/tech/950564/schlage-sense-pro-uwb-aliro-deadlock-price-availability',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/ENTRYWAY_BE889_SEP622_DAV_COL_EXT_IU_01-1.jpg?quality=90&strip=all&crop=0%2C11.874755925629%2C100%2C76.250488148741&w=1200',
  'publishedAt': '2026-06-16T11:37:08Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nThe Schlage Sense Pro will work with Apples Home Key hands-free unlocking and is its first to support Matter and Thread.\r\nThe Schlage Sense Pro will work with Ap… [+3213 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'John.Higgins',
  'title': 'These are my favorite Prime Day deals on earbuds and headphones',
  'description': 'I can’t think of a tech accessory I actively use more than headphones. Whether it’s for music, calls, or just to block out ambient noise so I can focus, I always have a pair close at hand. One of the best times to get some of your own with some big savings at…',
  'url': 'https://www.theverge.com/gadgets/952601/earbuds-headphones-deals-prime-day-2026',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/chorus/uploads/chorus_asset/file/23454336/DSCF7813.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
  'publishedAt': '2026-06-23T12:06:56Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nNeed ANC, great sound, and something for a workout? Prime Day is the time to get some new headphones.\r\nNeed ANC, great sound, and something for a workout? Prime … [+5856 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Cameron Faulkner',
  'title': 'The best early Amazon Prime Day deals so far',

In [4]:
articles_df = pd.DataFrame(articles)
articles_df.head()

,source,author,title,description,url,urlToImage,publishedAt,content
0,"{'id': 'wired', 'name': 'Wired'}",Louryn Strampe,"Prime Day Means Apple Deals on iPad, iPhone Ca...",Apple deals abound for Amazon Prime Day. We've...,https://www.wired.com/story/best-prime-day-app...,https://media.wired.com/photos/6a39bf7f0bf55f5...,2026-06-23T08:57:27Z,Amazon Prime Day is one of the most reliable w...
1,"{'id': 'wired', 'name': 'Wired'}",Julian Chokkattu,How Apple Is Making Your Older iPhone Run Fast...,Even the aging iPhone 11 will feel a little mo...,https://www.wired.com/story/how-apple-is-makin...,https://media.wired.com/photos/6a2aabf0a0ec339...,2026-06-15T10:30:00Z,Your aging iPhone will feel a little more resp...
2,"{'id': 'wired', 'name': 'Wired'}",Louryn Strampe,"Verizon Simplicity, Verizon Shine, and Verizon...",Verizon introduced a new plan that costs $45 p...,https://www.wired.com/story/verizon-simplicity...,https://media.wired.com/photos/6a303c55d7c81c3...,2026-06-16T15:06:22Z,I've been aVerizon customer since T-Mobile and...
3,"{'id': 'wired', 'name': 'Wired'}",Boutayna Chokrane,Best Prime Day Fitness Tech Deals (2026),Shopping Amazon's sale for yourself or a loved...,https://www.wired.com/story/amazon-prime-day-f...,https://media.wired.com/photos/6a3a246397b3e5b...,2026-06-23T09:32:14Z,"For Amazon's summer sale event, I've compiled ..."
4,"{'id': 'wired', 'name': 'Wired'}",Maxwell Zeff,The White House Is Making Up Its Rules for AI ...,Anthropic still can’t distribute Claude Mythos...,https://www.wired.com/story/anthropic-mythos-e...,https://media.wired.com/photos/6a342bff039398b...,2026-06-18T21:03:43Z,Its been nearly a week since the Trump adminis...

In [5]:
articles_df.drop(columns={'source', 'urlToImage'}, inplace=True)
articles_df.head()

,author,title,description,url,publishedAt,content
0,Louryn Strampe,"Prime Day Means Apple Deals on iPad, iPhone Ca...",Apple deals abound for Amazon Prime Day. We've...,https://www.wired.com/story/best-prime-day-app...,2026-06-23T08:57:27Z,Amazon Prime Day is one of the most reliable w...
1,Julian Chokkattu,How Apple Is Making Your Older iPhone Run Fast...,Even the aging iPhone 11 will feel a little mo...,https://www.wired.com/story/how-apple-is-makin...,2026-06-15T10:30:00Z,Your aging iPhone will feel a little more resp...
2,Louryn Strampe,"Verizon Simplicity, Verizon Shine, and Verizon...",Verizon introduced a new plan that costs $45 p...,https://www.wired.com/story/verizon-simplicity...,2026-06-16T15:06:22Z,I've been aVerizon customer since T-Mobile and...
3,Boutayna Chokrane,Best Prime Day Fitness Tech Deals (2026),Shopping Amazon's sale for yourself or a loved...,https://www.wired.com/story/amazon-prime-day-f...,2026-06-23T09:32:14Z,"For Amazon's summer sale event, I've compiled ..."
4,Maxwell Zeff,The White House Is Making Up Its Rules for AI ...,Anthropic still can’t distribute Claude Mythos...,https://www.wired.com/story/anthropic-mythos-e...,2026-06-18T21:03:43Z,Its been nearly a week since the Trump adminis...

In [6]:
load_dotenv()
DB_HOST = os.getenv('DB_HOST')
DB_PORT = os.getenv('DB_PORT')
DB_NAME = os.getenv('DB_NAME')
DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')

engine = create_engine(f'postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}')

articles_df.to_sql('articles', con=engine, if_exists='replace', index=False)

84